launch:
- node:
    pkg: "image_tools"
    exec: "cam2image"
    args: "--ros-args -p depth:=1 -p show_camera:=true"
    name: "cam"
    
      
- node:
    remap:
    - 
      to: /image
      from: /webcam_input
    -
      from: /setpoint
      to: /radians
    pkg: "jiwy_simulator"
    exec: "jiwy_simulator"
    name: "sim"

- node:
    ros__parameters:
      threshold: 254.0
    pkg: "light_level"
    exec: "light_position"

- node:
    pkg: "light_level"
    exec: "pix2rad"
    remap:
    -
      to: /light_position
      from: /pixels


- node:
    remap:
    - 
      from: /image
      to: /moving_camera_output
    pkg: "image_tools"
    exec: "showimage"